cert_exploremelon:
	sudo certbot certonly  --dns-cloudflare --dns-cloudflare-credentials dns-credentials/cloudflare.ini -d exploremelon.com -d '*.exploremelon.com' --email info@exploremelon.com --agree-tos --non-interactive --force-renewal --cert-name exploremelon.com --keep-until-expiring --rsa-key-size 4096 

cert_renewe:
	sudo certbot certonly  --dns-cloudflare --dns-cloudflare-credentials dns-credentials/cloudflare.ini  renew --cert-name $(name)

cert_bznspro:
	sudo certbot certonly  --dns-cloudflare --dns-cloudflare-credentials dns-credentials/ahmeddarwish_cloudflare.ini -d businessprosa.com -d '*.businessprosa.com' --email info@businessprosa.com --agree-tos --non-interactive --force-renewal --cert-name businessprosa.com --keep-until-expiring --rsa-key-size 4096 
 
cert_estabraq:
	sudo certbot certonly  --dns-cloudflare --dns-cloudflare-credentials dns-credentials/ahmeddarwish_cloudflare.ini -d estabraqsa.com -d '*.estabraqsa.com' --email info@estabraqsa.com --agree-tos --non-interactive --force-renewal --cert-name estabraqsa.com --keep-until-expiring --rsa-key-size 4096 
 


cert_hamatalkhalij:
	sudo certbot certonly  --dns-cloudflare --dns-cloudflare-credentials dns-credentials/ahmeddarwish_cloudflare.ini -d hamatalkhalij.com -d '*.hamatalkhalij.com' --email info@hamatalkhalij.com --agree-tos --non-interactive --force-renewal --cert-name hamatalkhalij.com --keep-until-expiring --rsa-key-size 4096 

cert_psi:
	sudo certbot certonly  --dns-cloudflare --dns-cloudflare-credentials dns-credentials/ahmeddarwish_cloudflare.ini -d psipacking.com -d '*.psipacking.com' --email info@psipacking.com --agree-tos --non-interactive --force-renewal --cert-name psipacking.com --keep-until-expiring --rsa-key-size 4096 
 

 