version: "3"
services:
  redis_db:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    restart: always

    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - nginx

networks:
  nginx:
    external: true

